### ISSUE TITLE
Cannot read property 'cpu' of null

### ISSUE THREAD

**Issue by mick340** [citizenfx/txAdmin#5]
Hi man,

Great script i love it. But there is only one issue my console is getting spammed with the following error:

`[FXAdmin:Monitor] Players online: 23
[FXAdmin:Monitor] Error refreshing processes statuses
TypeError: Cannot read property 'cpu' of null
    at Object.keys.forEach (/home/digit/fivem-test/fivem-fxadmin/src/components/monitor.js:180:38)
    at Array.forEach (<anonymous>)
    at Monitor.refreshProcessStatus (/home/digit/fivem-test/fivem-fxadmin/src/components/monitor.js:175:36)`

Any idea on how to resolve this? 

Im running Linux on a VPS server :)

**Comment by mick340** [comment]
Fixed

**Comment by tabarra** [comment]
Will be fixed in the next Update.
